version: '3.8'
services:
  ipam-ui-custom:
    build:
      context: ./ui
      dockerfile: Dockerfile.custom
      args:
        PORT: 8081
    environment:
      REACT_APP_AZURE_ENV: ${AZURE_ENV}
      REACT_APP_UI_ID: ${UI_APP_ID}
      REACT_APP_ENGINE_ID: ${ENGINE_APP_ID}
      REACT_APP_TENANT_ID: ${TENANT_ID}
      WDS_SOCKET_PORT: 3000
    volumes:
      - ./ui:/app
      - /app/node_modules
    networks:
      my-network-name:
        aliases:
          - ipam-ui-name
  ipam-engine-custom:
    build:
      context: ./engine
      dockerfile: Dockerfile.custom
      args:
        PORT: 8082
    environment:
      CLIENT_ID: ${ENGINE_APP_ID}
      CLIENT_SECRET: ${ENGINE_APP_SECRET}
      TENANT_ID: ${TENANT_ID}
      COSMOS_URL: ${COSMOS_URL}
      COSMOS_KEY: ${COSMOS_KEY}
      KEYVAULT_URL: ${KEYVAULT_URL}
    volumes:
      - ./engine/app:/code/app
    networks:
      my-network-name:
        aliases:
          - ipam-engine-name
  nginx-proxy-custom:
    depends_on:
      - ipam-ui-custom
      - ipam-engine-custom
    build:
      context: ./lb
      dockerfile: Dockerfile.custom
    networks:
      my-network-name:
        aliases:
          - proxy-name
    ports:
      - "3000:8080"
networks:
  my-network-name:
